Fixes to tutorial notebooks
norse/notebooks pull request #6
Opened 2021-03-04 11:55 UTC by adelpierre

2021-03-04 15:17 UTC, Jegp requested changes
Great work Adrien. I admire your eye for detail. You've linked to documentation and clarified the text greatly, so this is a nice contribution.

I also like that you included pictures, so people can actually just skim through it if they don't want to do the notebook.

There's one problem in the norse tutorial notebook, where one of the cells fail because it was interrupted. That should be run more efficiently.

Tomorrow, we can perhaps look at fixing your CUDA drivers. And then I can give you access to a machine with much more GPU power that should be helpful.

2021-03-04 15:17 UTC, Jegp commented on spiking_introduction.ipynb
> +    "To start simulating we need to create a population of LIF neurons of an arbitrary size. Each neuron in the population is set to a default state. This default state tells us what the initial neur
Nice reference! :)

2021-03-13 13:31 UTC, Jegp commented
Any news on this @adelpierre ?

2021-03-15 16:11 UTC, adelpierre commented
Should be fixed with the latest commit !

2021-03-16 20:57 UTC, Jegp commented
Nice work :-)

2021-03-16 20:57 UTC, merged